version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - storeDB:/var/lib/mysql
    ports:
      - '3306:3306'

  app:
    build: .
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - '${PORT}:${PORT}'
    command: >
      sh -c "
        bun prisma generate &&
        bun --watch src/server.ts
      "

volumes:
  storeDB:
