version: '3.8'

services:
  db:
    image: mysql:8.0
    env_file: .env
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - storeDB:/var/lib/mysql
    ports:
      - '3306:3306'

volumes:
  storeDB:
